# Website title
title = "argument"
logo = """
                                                 __   
_____ _______  ____  __ __  _____   ____   _____/  |_ 
\\__  \\\\_  __ \\/ ___\\|  |  \\/     \\_/ __ \\ /    \\   __\\
 / __ \\|  | \\/ /_/  >  |  /  Y Y  \\  ___/|   |  \\  |  
(____  /__|  \\___  /|____/|__|_|  /\\___  >___|  /__|  
     \\/     /_____/             \\/     \\/     \\/      
"""
